# Generated by Django 6.0.2 on 2026-03-12 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Duration Hours')),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Price')),
                ('max_students', models.PositiveIntegerField(default=20, verbose_name='Max Students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'course_mgmt_course',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('instructor_id', models.UUIDField(blank=True, null=True, verbose_name='Instructor Id')),
                ('instructor_name', models.CharField(blank=True, max_length=255, verbose_name='Instructor Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='Enrolled Count')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course_mgmt.course')),
            ],
            options={
                'db_table': 'course_mgmt_classsession',
                'abstract': False,
            },
        ),
    ]
